"""Declarative base and shared column conventions."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Deterministic constraint names. Without this, Alembic autogenerate produces migrations
#: that cannot drop the constraints an earlier migration created, because the database
#: assigned them arbitrary names.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    metadata = metadata

    # Fetch server-generated values (``created_at``, and ``updated_at`` on UPDATE) in the
    # same statement via RETURNING. Without this, SQLAlchemy expires those attributes after
    # a flush and reading one later triggers lazy IO — which, under asyncio, raises
    # MissingGreenlet rather than quietly issuing a second query.
    __mapper_args__ = {"eager_defaults": True}  # noqa: RUF012 - SQLAlchemy API

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy API
        dict[str, Any]: JSONB,
        UUID: PG_UUID(as_uuid=True),
    }


class TimestampMixin:
    """``created_at`` / ``updated_at``, both database-generated.

    Generated by the database rather than the application so that a direct SQL fix or a
    migration cannot leave a row with no timestamps.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
